[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"
rand = "0.8"
threadpool = "1.8"
assert_approx_eq = "1.1.0"
rayon = "1.6"
